[project]
name = "eppv-github-io"
version = "0.1.0"
description = "Personal GitHub Pages site"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.15",
]
